// <auto-generated />
using LTW_Day09Lab_CodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LTW_Day09Lab_CodeFirst.Migrations
{
    [DbContext(typeof(TvcDay09LabCFContext))]
    partial class TvcDay09LabCFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LTW_Day09Lab_CodeFirst.Models.TvcLoaiSanPham", b =>
                {
                    b.Property<long>("tvcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("tvcId"));

                    b.Property<string>("tvcMaLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tvcTenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("tvcTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("tvcId");

                    b.HasIndex("tvcMaLoai")
                        .IsUnique();

                    b.ToTable("TvcLoaiSanPham");
                });

            modelBuilder.Entity("LTW_Day09Lab_CodeFirst.Models.TvcSanPham", b =>
                {
                    b.Property<long>("tvcID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("tvcID"));

                    b.Property<decimal>("tvcDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tvcHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tvcLoaiSanPhamID")
                        .HasColumnType("bigint");

                    b.Property<string>("tvcMaSanPham")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("tvcSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("tvcTenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tvcID");

                    b.HasIndex("tvcLoaiSanPhamID");

                    b.ToTable("TvcSanPham");
                });

            modelBuilder.Entity("LTW_Day09Lab_CodeFirst.Models.TvcSanPham", b =>
                {
                    b.HasOne("LTW_Day09Lab_CodeFirst.Models.TvcLoaiSanPham", "TvcLoaiSanPham")
                        .WithMany("tvcSanPhams")
                        .HasForeignKey("tvcLoaiSanPhamID");

                    b.Navigation("TvcLoaiSanPham");
                });

            modelBuilder.Entity("LTW_Day09Lab_CodeFirst.Models.TvcLoaiSanPham", b =>
                {
                    b.Navigation("tvcSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
